/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateConnectorResponseTasksInner struct for CreateConnectorResponseTasksInner
type CreateConnectorResponseTasksInner struct {
	// Name of the connector.
	Connector *string `json:"connector,omitempty"`
	// ID of the task.
	Task *int32 `json:"task,omitempty"`
}

// NewCreateConnectorResponseTasksInner instantiates a new CreateConnectorResponseTasksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConnectorResponseTasksInner() *CreateConnectorResponseTasksInner {
	this := CreateConnectorResponseTasksInner{}
	return &this
}

// NewCreateConnectorResponseTasksInnerWithDefaults instantiates a new CreateConnectorResponseTasksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConnectorResponseTasksInnerWithDefaults() *CreateConnectorResponseTasksInner {
	this := CreateConnectorResponseTasksInner{}
	return &this
}

// GetConnector returns the Connector field value if set, zero value otherwise.
func (o *CreateConnectorResponseTasksInner) GetConnector() string {
	if o == nil || o.Connector == nil {
		var ret string
		return ret
	}
	return *o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorResponseTasksInner) GetConnectorOk() (*string, bool) {
	if o == nil || o.Connector == nil {
		return nil, false
	}
	return o.Connector, true
}

// HasConnector returns a boolean if a field has been set.
func (o *CreateConnectorResponseTasksInner) HasConnector() bool {
	if o != nil && o.Connector != nil {
		return true
	}

	return false
}

// SetConnector gets a reference to the given string and assigns it to the Connector field.
func (o *CreateConnectorResponseTasksInner) SetConnector(v string) {
	o.Connector = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *CreateConnectorResponseTasksInner) GetTask() int32 {
	if o == nil || o.Task == nil {
		var ret int32
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorResponseTasksInner) GetTaskOk() (*int32, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *CreateConnectorResponseTasksInner) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given int32 and assigns it to the Task field.
func (o *CreateConnectorResponseTasksInner) SetTask(v int32) {
	o.Task = &v
}

func (o CreateConnectorResponseTasksInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Connector != nil {
		toSerialize["connector"] = o.Connector
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	return json.Marshal(toSerialize)
}

type NullableCreateConnectorResponseTasksInner struct {
	value *CreateConnectorResponseTasksInner
	isSet bool
}

func (v NullableCreateConnectorResponseTasksInner) Get() *CreateConnectorResponseTasksInner {
	return v.value
}

func (v *NullableCreateConnectorResponseTasksInner) Set(val *CreateConnectorResponseTasksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConnectorResponseTasksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConnectorResponseTasksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConnectorResponseTasksInner(val *CreateConnectorResponseTasksInner) *NullableCreateConnectorResponseTasksInner {
	return &NullableCreateConnectorResponseTasksInner{value: val, isSet: true}
}

func (v NullableCreateConnectorResponseTasksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConnectorResponseTasksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


