/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListConnectorsResponseValueInfoTasksInner struct for ListConnectorsResponseValueInfoTasksInner
type ListConnectorsResponseValueInfoTasksInner struct {
	// Name of the connector.
	Connector *string `json:"connector,omitempty"`
	// ID of the task.
	Task *int32 `json:"task,omitempty"`
	// Configuration of a connector/task/worker. All keys/values should be strings.
	Config *map[string]string `json:"config,omitempty"`
}

// NewListConnectorsResponseValueInfoTasksInner instantiates a new ListConnectorsResponseValueInfoTasksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnectorsResponseValueInfoTasksInner() *ListConnectorsResponseValueInfoTasksInner {
	this := ListConnectorsResponseValueInfoTasksInner{}
	return &this
}

// NewListConnectorsResponseValueInfoTasksInnerWithDefaults instantiates a new ListConnectorsResponseValueInfoTasksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnectorsResponseValueInfoTasksInnerWithDefaults() *ListConnectorsResponseValueInfoTasksInner {
	this := ListConnectorsResponseValueInfoTasksInner{}
	return &this
}

// GetConnector returns the Connector field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfoTasksInner) GetConnector() string {
	if o == nil || o.Connector == nil {
		var ret string
		return ret
	}
	return *o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfoTasksInner) GetConnectorOk() (*string, bool) {
	if o == nil || o.Connector == nil {
		return nil, false
	}
	return o.Connector, true
}

// HasConnector returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfoTasksInner) HasConnector() bool {
	if o != nil && o.Connector != nil {
		return true
	}

	return false
}

// SetConnector gets a reference to the given string and assigns it to the Connector field.
func (o *ListConnectorsResponseValueInfoTasksInner) SetConnector(v string) {
	o.Connector = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfoTasksInner) GetTask() int32 {
	if o == nil || o.Task == nil {
		var ret int32
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfoTasksInner) GetTaskOk() (*int32, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfoTasksInner) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given int32 and assigns it to the Task field.
func (o *ListConnectorsResponseValueInfoTasksInner) SetTask(v int32) {
	o.Task = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfoTasksInner) GetConfig() map[string]string {
	if o == nil || o.Config == nil {
		var ret map[string]string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfoTasksInner) GetConfigOk() (*map[string]string, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfoTasksInner) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]string and assigns it to the Config field.
func (o *ListConnectorsResponseValueInfoTasksInner) SetConfig(v map[string]string) {
	o.Config = &v
}

func (o ListConnectorsResponseValueInfoTasksInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Connector != nil {
		toSerialize["connector"] = o.Connector
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableListConnectorsResponseValueInfoTasksInner struct {
	value *ListConnectorsResponseValueInfoTasksInner
	isSet bool
}

func (v NullableListConnectorsResponseValueInfoTasksInner) Get() *ListConnectorsResponseValueInfoTasksInner {
	return v.value
}

func (v *NullableListConnectorsResponseValueInfoTasksInner) Set(val *ListConnectorsResponseValueInfoTasksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnectorsResponseValueInfoTasksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnectorsResponseValueInfoTasksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnectorsResponseValueInfoTasksInner(val *ListConnectorsResponseValueInfoTasksInner) *NullableListConnectorsResponseValueInfoTasksInner {
	return &NullableListConnectorsResponseValueInfoTasksInner{value: val, isSet: true}
}

func (v NullableListConnectorsResponseValueInfoTasksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnectorsResponseValueInfoTasksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


