/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListConnectorsResponseValueStatus struct for ListConnectorsResponseValueStatus
type ListConnectorsResponseValueStatus struct {
	// Name of the connector.
	Name *string `json:"name,omitempty"`
	Type *ConnectorType `json:"type,omitempty"`
	Connector *ListConnectorsResponseValueStatusConnector `json:"connector,omitempty"`
	// List of task statuses for the connector.
	Tasks []ListConnectorsResponseValueStatusTasksInner `json:"tasks,omitempty"`
}

// NewListConnectorsResponseValueStatus instantiates a new ListConnectorsResponseValueStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnectorsResponseValueStatus() *ListConnectorsResponseValueStatus {
	this := ListConnectorsResponseValueStatus{}
	return &this
}

// NewListConnectorsResponseValueStatusWithDefaults instantiates a new ListConnectorsResponseValueStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnectorsResponseValueStatusWithDefaults() *ListConnectorsResponseValueStatus {
	this := ListConnectorsResponseValueStatus{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueStatus) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueStatus) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueStatus) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListConnectorsResponseValueStatus) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueStatus) GetType() ConnectorType {
	if o == nil || o.Type == nil {
		var ret ConnectorType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueStatus) GetTypeOk() (*ConnectorType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueStatus) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given ConnectorType and assigns it to the Type field.
func (o *ListConnectorsResponseValueStatus) SetType(v ConnectorType) {
	o.Type = &v
}

// GetConnector returns the Connector field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueStatus) GetConnector() ListConnectorsResponseValueStatusConnector {
	if o == nil || o.Connector == nil {
		var ret ListConnectorsResponseValueStatusConnector
		return ret
	}
	return *o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueStatus) GetConnectorOk() (*ListConnectorsResponseValueStatusConnector, bool) {
	if o == nil || o.Connector == nil {
		return nil, false
	}
	return o.Connector, true
}

// HasConnector returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueStatus) HasConnector() bool {
	if o != nil && o.Connector != nil {
		return true
	}

	return false
}

// SetConnector gets a reference to the given ListConnectorsResponseValueStatusConnector and assigns it to the Connector field.
func (o *ListConnectorsResponseValueStatus) SetConnector(v ListConnectorsResponseValueStatusConnector) {
	o.Connector = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueStatus) GetTasks() []ListConnectorsResponseValueStatusTasksInner {
	if o == nil || o.Tasks == nil {
		var ret []ListConnectorsResponseValueStatusTasksInner
		return ret
	}
	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueStatus) GetTasksOk() ([]ListConnectorsResponseValueStatusTasksInner, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueStatus) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []ListConnectorsResponseValueStatusTasksInner and assigns it to the Tasks field.
func (o *ListConnectorsResponseValueStatus) SetTasks(v []ListConnectorsResponseValueStatusTasksInner) {
	o.Tasks = v
}

func (o ListConnectorsResponseValueStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Connector != nil {
		toSerialize["connector"] = o.Connector
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	return json.Marshal(toSerialize)
}

type NullableListConnectorsResponseValueStatus struct {
	value *ListConnectorsResponseValueStatus
	isSet bool
}

func (v NullableListConnectorsResponseValueStatus) Get() *ListConnectorsResponseValueStatus {
	return v.value
}

func (v *NullableListConnectorsResponseValueStatus) Set(val *ListConnectorsResponseValueStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnectorsResponseValueStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnectorsResponseValueStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnectorsResponseValueStatus(val *ListConnectorsResponseValueStatus) *NullableListConnectorsResponseValueStatus {
	return &NullableListConnectorsResponseValueStatus{value: val, isSet: true}
}

func (v NullableListConnectorsResponseValueStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnectorsResponseValueStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


