/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListConnectorTasksResponseTasksInner struct for ListConnectorTasksResponseTasksInner
type ListConnectorTasksResponseTasksInner struct {
	Id *ListConnectorTasksResponseTasksInnerId `json:"id,omitempty"`
	// Configuration of a connector/task/worker. All keys/values should be strings.
	Config *map[string]string `json:"config,omitempty"`
}

// NewListConnectorTasksResponseTasksInner instantiates a new ListConnectorTasksResponseTasksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnectorTasksResponseTasksInner() *ListConnectorTasksResponseTasksInner {
	this := ListConnectorTasksResponseTasksInner{}
	return &this
}

// NewListConnectorTasksResponseTasksInnerWithDefaults instantiates a new ListConnectorTasksResponseTasksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnectorTasksResponseTasksInnerWithDefaults() *ListConnectorTasksResponseTasksInner {
	this := ListConnectorTasksResponseTasksInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListConnectorTasksResponseTasksInner) GetId() ListConnectorTasksResponseTasksInnerId {
	if o == nil || o.Id == nil {
		var ret ListConnectorTasksResponseTasksInnerId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorTasksResponseTasksInner) GetIdOk() (*ListConnectorTasksResponseTasksInnerId, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListConnectorTasksResponseTasksInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given ListConnectorTasksResponseTasksInnerId and assigns it to the Id field.
func (o *ListConnectorTasksResponseTasksInner) SetId(v ListConnectorTasksResponseTasksInnerId) {
	o.Id = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *ListConnectorTasksResponseTasksInner) GetConfig() map[string]string {
	if o == nil || o.Config == nil {
		var ret map[string]string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorTasksResponseTasksInner) GetConfigOk() (*map[string]string, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *ListConnectorTasksResponseTasksInner) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]string and assigns it to the Config field.
func (o *ListConnectorTasksResponseTasksInner) SetConfig(v map[string]string) {
	o.Config = &v
}

func (o ListConnectorTasksResponseTasksInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableListConnectorTasksResponseTasksInner struct {
	value *ListConnectorTasksResponseTasksInner
	isSet bool
}

func (v NullableListConnectorTasksResponseTasksInner) Get() *ListConnectorTasksResponseTasksInner {
	return v.value
}

func (v *NullableListConnectorTasksResponseTasksInner) Set(val *ListConnectorTasksResponseTasksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnectorTasksResponseTasksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnectorTasksResponseTasksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnectorTasksResponseTasksInner(val *ListConnectorTasksResponseTasksInner) *NullableListConnectorTasksResponseTasksInner {
	return &NullableListConnectorTasksResponseTasksInner{value: val, isSet: true}
}

func (v NullableListConnectorTasksResponseTasksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnectorTasksResponseTasksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


