/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListConnectorsResponseValueInfo struct for ListConnectorsResponseValueInfo
type ListConnectorsResponseValueInfo struct {
	// Name of the connector.
	Name *string `json:"name,omitempty"`
	Type *ConnectorType `json:"type,omitempty"`
	// Configuration of a connector/task/worker. All keys/values should be strings.
	Config *map[string]string `json:"config,omitempty"`
	// List of tasks for the connector.
	Tasks []ListConnectorsResponseValueInfoTasksInner `json:"tasks,omitempty"`
}

// NewListConnectorsResponseValueInfo instantiates a new ListConnectorsResponseValueInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnectorsResponseValueInfo() *ListConnectorsResponseValueInfo {
	this := ListConnectorsResponseValueInfo{}
	return &this
}

// NewListConnectorsResponseValueInfoWithDefaults instantiates a new ListConnectorsResponseValueInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnectorsResponseValueInfoWithDefaults() *ListConnectorsResponseValueInfo {
	this := ListConnectorsResponseValueInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListConnectorsResponseValueInfo) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfo) GetType() ConnectorType {
	if o == nil || o.Type == nil {
		var ret ConnectorType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfo) GetTypeOk() (*ConnectorType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfo) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given ConnectorType and assigns it to the Type field.
func (o *ListConnectorsResponseValueInfo) SetType(v ConnectorType) {
	o.Type = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfo) GetConfig() map[string]string {
	if o == nil || o.Config == nil {
		var ret map[string]string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfo) GetConfigOk() (*map[string]string, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfo) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]string and assigns it to the Config field.
func (o *ListConnectorsResponseValueInfo) SetConfig(v map[string]string) {
	o.Config = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *ListConnectorsResponseValueInfo) GetTasks() []ListConnectorsResponseValueInfoTasksInner {
	if o == nil || o.Tasks == nil {
		var ret []ListConnectorsResponseValueInfoTasksInner
		return ret
	}
	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorsResponseValueInfo) GetTasksOk() ([]ListConnectorsResponseValueInfoTasksInner, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *ListConnectorsResponseValueInfo) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []ListConnectorsResponseValueInfoTasksInner and assigns it to the Tasks field.
func (o *ListConnectorsResponseValueInfo) SetTasks(v []ListConnectorsResponseValueInfoTasksInner) {
	o.Tasks = v
}

func (o ListConnectorsResponseValueInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	return json.Marshal(toSerialize)
}

type NullableListConnectorsResponseValueInfo struct {
	value *ListConnectorsResponseValueInfo
	isSet bool
}

func (v NullableListConnectorsResponseValueInfo) Get() *ListConnectorsResponseValueInfo {
	return v.value
}

func (v *NullableListConnectorsResponseValueInfo) Set(val *ListConnectorsResponseValueInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnectorsResponseValueInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnectorsResponseValueInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnectorsResponseValueInfo(val *ListConnectorsResponseValueInfo) *NullableListConnectorsResponseValueInfo {
	return &NullableListConnectorsResponseValueInfo{value: val, isSet: true}
}

func (v NullableListConnectorsResponseValueInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnectorsResponseValueInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


