/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectorStatusResponseConnector Connector status.
type GetConnectorStatusResponseConnector struct {
	State *State `json:"state,omitempty"`
	// ID of the worker.
	WorkerId *string `json:"worker_id,omitempty"`
}

// NewGetConnectorStatusResponseConnector instantiates a new GetConnectorStatusResponseConnector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectorStatusResponseConnector() *GetConnectorStatusResponseConnector {
	this := GetConnectorStatusResponseConnector{}
	return &this
}

// NewGetConnectorStatusResponseConnectorWithDefaults instantiates a new GetConnectorStatusResponseConnector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectorStatusResponseConnectorWithDefaults() *GetConnectorStatusResponseConnector {
	this := GetConnectorStatusResponseConnector{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GetConnectorStatusResponseConnector) GetState() State {
	if o == nil || o.State == nil {
		var ret State
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorStatusResponseConnector) GetStateOk() (*State, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GetConnectorStatusResponseConnector) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given State and assigns it to the State field.
func (o *GetConnectorStatusResponseConnector) SetState(v State) {
	o.State = &v
}

// GetWorkerId returns the WorkerId field value if set, zero value otherwise.
func (o *GetConnectorStatusResponseConnector) GetWorkerId() string {
	if o == nil || o.WorkerId == nil {
		var ret string
		return ret
	}
	return *o.WorkerId
}

// GetWorkerIdOk returns a tuple with the WorkerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorStatusResponseConnector) GetWorkerIdOk() (*string, bool) {
	if o == nil || o.WorkerId == nil {
		return nil, false
	}
	return o.WorkerId, true
}

// HasWorkerId returns a boolean if a field has been set.
func (o *GetConnectorStatusResponseConnector) HasWorkerId() bool {
	if o != nil && o.WorkerId != nil {
		return true
	}

	return false
}

// SetWorkerId gets a reference to the given string and assigns it to the WorkerId field.
func (o *GetConnectorStatusResponseConnector) SetWorkerId(v string) {
	o.WorkerId = &v
}

func (o GetConnectorStatusResponseConnector) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.WorkerId != nil {
		toSerialize["worker_id"] = o.WorkerId
	}
	return json.Marshal(toSerialize)
}

type NullableGetConnectorStatusResponseConnector struct {
	value *GetConnectorStatusResponseConnector
	isSet bool
}

func (v NullableGetConnectorStatusResponseConnector) Get() *GetConnectorStatusResponseConnector {
	return v.value
}

func (v *NullableGetConnectorStatusResponseConnector) Set(val *GetConnectorStatusResponseConnector) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectorStatusResponseConnector) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectorStatusResponseConnector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectorStatusResponseConnector(val *GetConnectorStatusResponseConnector) *NullableGetConnectorStatusResponseConnector {
	return &NullableGetConnectorStatusResponseConnector{value: val, isSet: true}
}

func (v NullableGetConnectorStatusResponseConnector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectorStatusResponseConnector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


