/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListConnectorTasksResponseTasksInnerId Task ID.
type ListConnectorTasksResponseTasksInnerId struct {
	// ID of the task.
	Task *int32 `json:"task,omitempty"`
	// Name of the connector.
	Connector *string `json:"connector,omitempty"`
}

// NewListConnectorTasksResponseTasksInnerId instantiates a new ListConnectorTasksResponseTasksInnerId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnectorTasksResponseTasksInnerId() *ListConnectorTasksResponseTasksInnerId {
	this := ListConnectorTasksResponseTasksInnerId{}
	return &this
}

// NewListConnectorTasksResponseTasksInnerIdWithDefaults instantiates a new ListConnectorTasksResponseTasksInnerId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnectorTasksResponseTasksInnerIdWithDefaults() *ListConnectorTasksResponseTasksInnerId {
	this := ListConnectorTasksResponseTasksInnerId{}
	return &this
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *ListConnectorTasksResponseTasksInnerId) GetTask() int32 {
	if o == nil || o.Task == nil {
		var ret int32
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorTasksResponseTasksInnerId) GetTaskOk() (*int32, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *ListConnectorTasksResponseTasksInnerId) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given int32 and assigns it to the Task field.
func (o *ListConnectorTasksResponseTasksInnerId) SetTask(v int32) {
	o.Task = &v
}

// GetConnector returns the Connector field value if set, zero value otherwise.
func (o *ListConnectorTasksResponseTasksInnerId) GetConnector() string {
	if o == nil || o.Connector == nil {
		var ret string
		return ret
	}
	return *o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorTasksResponseTasksInnerId) GetConnectorOk() (*string, bool) {
	if o == nil || o.Connector == nil {
		return nil, false
	}
	return o.Connector, true
}

// HasConnector returns a boolean if a field has been set.
func (o *ListConnectorTasksResponseTasksInnerId) HasConnector() bool {
	if o != nil && o.Connector != nil {
		return true
	}

	return false
}

// SetConnector gets a reference to the given string and assigns it to the Connector field.
func (o *ListConnectorTasksResponseTasksInnerId) SetConnector(v string) {
	o.Connector = &v
}

func (o ListConnectorTasksResponseTasksInnerId) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	if o.Connector != nil {
		toSerialize["connector"] = o.Connector
	}
	return json.Marshal(toSerialize)
}

type NullableListConnectorTasksResponseTasksInnerId struct {
	value *ListConnectorTasksResponseTasksInnerId
	isSet bool
}

func (v NullableListConnectorTasksResponseTasksInnerId) Get() *ListConnectorTasksResponseTasksInnerId {
	return v.value
}

func (v *NullableListConnectorTasksResponseTasksInnerId) Set(val *ListConnectorTasksResponseTasksInnerId) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnectorTasksResponseTasksInnerId) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnectorTasksResponseTasksInnerId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnectorTasksResponseTasksInnerId(val *ListConnectorTasksResponseTasksInnerId) *NullableListConnectorTasksResponseTasksInnerId {
	return &NullableListConnectorTasksResponseTasksInnerId{value: val, isSet: true}
}

func (v NullableListConnectorTasksResponseTasksInnerId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnectorTasksResponseTasksInnerId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


