/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetClusterInfoResponse struct for GetClusterInfoResponse
type GetClusterInfoResponse struct {
	// Connect worker version.
	Version *string `json:"version,omitempty"`
	// git commit ID.
	Commit *string `json:"commit,omitempty"`
	// Kafka cluster ID.
	KafkaClusterId *string `json:"kafka_cluster_id,omitempty"`
}

// NewGetClusterInfoResponse instantiates a new GetClusterInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterInfoResponse() *GetClusterInfoResponse {
	this := GetClusterInfoResponse{}
	return &this
}

// NewGetClusterInfoResponseWithDefaults instantiates a new GetClusterInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterInfoResponseWithDefaults() *GetClusterInfoResponse {
	this := GetClusterInfoResponse{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetClusterInfoResponse) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterInfoResponse) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetClusterInfoResponse) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetClusterInfoResponse) SetVersion(v string) {
	o.Version = &v
}

// GetCommit returns the Commit field value if set, zero value otherwise.
func (o *GetClusterInfoResponse) GetCommit() string {
	if o == nil || o.Commit == nil {
		var ret string
		return ret
	}
	return *o.Commit
}

// GetCommitOk returns a tuple with the Commit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterInfoResponse) GetCommitOk() (*string, bool) {
	if o == nil || o.Commit == nil {
		return nil, false
	}
	return o.Commit, true
}

// HasCommit returns a boolean if a field has been set.
func (o *GetClusterInfoResponse) HasCommit() bool {
	if o != nil && o.Commit != nil {
		return true
	}

	return false
}

// SetCommit gets a reference to the given string and assigns it to the Commit field.
func (o *GetClusterInfoResponse) SetCommit(v string) {
	o.Commit = &v
}

// GetKafkaClusterId returns the KafkaClusterId field value if set, zero value otherwise.
func (o *GetClusterInfoResponse) GetKafkaClusterId() string {
	if o == nil || o.KafkaClusterId == nil {
		var ret string
		return ret
	}
	return *o.KafkaClusterId
}

// GetKafkaClusterIdOk returns a tuple with the KafkaClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterInfoResponse) GetKafkaClusterIdOk() (*string, bool) {
	if o == nil || o.KafkaClusterId == nil {
		return nil, false
	}
	return o.KafkaClusterId, true
}

// HasKafkaClusterId returns a boolean if a field has been set.
func (o *GetClusterInfoResponse) HasKafkaClusterId() bool {
	if o != nil && o.KafkaClusterId != nil {
		return true
	}

	return false
}

// SetKafkaClusterId gets a reference to the given string and assigns it to the KafkaClusterId field.
func (o *GetClusterInfoResponse) SetKafkaClusterId(v string) {
	o.KafkaClusterId = &v
}

func (o GetClusterInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Commit != nil {
		toSerialize["commit"] = o.Commit
	}
	if o.KafkaClusterId != nil {
		toSerialize["kafka_cluster_id"] = o.KafkaClusterId
	}
	return json.Marshal(toSerialize)
}

type NullableGetClusterInfoResponse struct {
	value *GetClusterInfoResponse
	isSet bool
}

func (v NullableGetClusterInfoResponse) Get() *GetClusterInfoResponse {
	return v.value
}

func (v *NullableGetClusterInfoResponse) Set(val *GetClusterInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterInfoResponse(val *GetClusterInfoResponse) *NullableGetClusterInfoResponse {
	return &NullableGetClusterInfoResponse{value: val, isSet: true}
}

func (v NullableGetClusterInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


